
// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0038:You should use expression bodied members whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:BorrowerRegistrationApplication.Controllers.BorrowerController.Get~System.Collections.Generic.IEnumerable{Data.Borrower}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0038:You should use expression bodied members whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:BorrowerRegistrationApplication.Controllers.BorrowerController.Get(System.Guid)~Data.Borrower")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0038:You should use expression bodied members whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:InterviewWebApp.Controllers.HomeController.Index~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0038:You should use expression bodied members whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:InterviewWebApp.Controllers.HomeController.Privacy~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0038:You should use expression bodied members whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:InterviewWebApp.Controllers.HomeController.Error~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0038:You should use expression bodied members whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:InterviewWebApp.Program.CreateWebHostBuilder(System.String[])~Microsoft.AspNetCore.Hosting.IWebHostBuilder")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0038:You should use expression bodied members whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:BorrowerRegistrationApplication.Controllers.BorrowersController.Index~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CC0070:Use ConfigureAwait(false) on awaited task.", Justification = "<Pending>", Scope = "member", Target = "~M:BorrowerRegistrationApplication.Controllers.BorrowersController.Details(System.Nullable{System.Guid})~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0038:You should use expression bodied members whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:BorrowerRegistrationApplication.Controllers.BorrowersController.BorrowerExists(System.Guid)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0038:You should use expression bodied members whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:BorrowerRegistrationApplication.Controllers.BorrowersController.IndexAsync~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CC0070:Use ConfigureAwait(false) on awaited task.", Justification = "<Pending>", Scope = "member", Target = "~M:BorrowerRegistrationApplication.Controllers.BorrowersController.Edit(System.Nullable{System.Guid})~System.Threading.Tasks.Task{Microsoft.AspNetCore.Mvc.IActionResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0038:You should use expression bodied members whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:BorrowerRegistrationApplication.Controllers.BorrowersController.Index~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0038:You should use expression bodied members whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:InterviewWebApp.Controllers.HomeController.Register~Microsoft.AspNetCore.Mvc.IActionResult")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0038:You should use expression bodied members whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:BorrowerRegistrationApplication.Controllers.BorrowersController.Edit~Microsoft.AspNetCore.Mvc.IActionResult")]

